### ISSUE TITLE
Bus stops should be shown for the current selected route

### ISSUE THREAD

**Issue by spybug** [spybug/GTCampusNavigation#27]
The bus stops should be drawn on the map for the currently selected route using our custom icon. 

When clicked, information about the stop should be shown related to the next buses coming to that stop and estimated times.

Filter out times greater 20 mins for now.

**Comment by JenaStark** [comment]
Bus stops are returned with the first prediction time from gtbuses

**Comment by JenaStark** [comment]
Bus predictions less than or equal to 30 minutes are now returned
